### ISSUE TITLE
Plugin does not work with PDN 4.3 / .NET 5

### ISSUE THREAD

**Issue by rickbrew** [NinthDesertDude/Brush-Factory#42]
Right-clicking in the canvas area will cause PDN to crash.

Should just be a matter of switching from `ContextMenu` to `ContextMenuStrip`.

`Menu` and `ContextMenu` were removed from WinForms back in .NET 3.1. Their use has been deprecated for 15 years anyway.

**Comment by rickbrew** [comment]
I have to add this plugin to the list of blocked effects to prevent the crashing. If you're planning on putting out an update, I can make sure it's tagged as having an update available (even if it's not yet available).

**Comment by NinthDesertDude** [comment]
Confirmed working with toehead's fix in both latest and alpha build. Thanks for logging the bug as well. I'll bump it shortly.

**Comment by rickbrew** [comment]
Thanks, I'll mark the plugin as "UpdateRequired" in Plugin Errors

**Comment by rickbrew** [comment]
Also, if the only change is to use the `*Strip` classes, you could probably defer porting to .NET 5 (which is easy but Yet Another Work Item) and still compile against PDN 4.2.16's DLLs and still target .NET 4.8. It should load fine n PDn 4.3. (although please verify with the portable copy of PDN 4.3; be sure to install the effects "locally" to it in its Effects folder)
